import {
  Shirt,
  Waves,
  Palmtree,
  Cross,
  Sparkles,
  SprayCan,
  Pill,
  Dumbbell,
  ToyBrick,
  Wifi,
  Smartphone,
  CreditCard,
  Landmark,
  Dices,
  Laptop,
  WashingMachine,
  Paperclip,
  Headphones,
  Home,
  Sofa,
  UtensilsCrossed,
  Coffee,
  ShoppingBasket,
  Baby,
  PawPrint,
  Car,
  Bike,
  Plane,
  Hotel,
  Gamepad2,
  Book,
  BookOpenText,
  GraduationCap,
  Stethoscope,
  Scissors,
  Gem,
  Watch,
  Footprints,
  Camera,
  Music,
  Wrench,
  Hammer,
  Leaf,
  Flower2,
  Gift,
  Ticket,
  Tv,
  Cloud,
  PiggyBank,
  Bitcoin,
  Receipt,
  Truck,
  Building2,
  Sun,
  type LucideIcon,
} from "lucide-react";

export type IconDef = {
  id: string;
  label: string;
  Icon: LucideIcon;
  gradient: string;
};

/** Biblioteca de ícones 3D com gradiente para categorias e redes sociais. */
export const ICON_LIBRARY: IconDef[] = [
  { id: "roupas", label: "Roupas", Icon: Shirt, gradient: "from-pink-400 to-rose-500" },
  { id: "moda-praia", label: "Moda praia e surf", Icon: Waves, gradient: "from-cyan-300 to-blue-600" },
  { id: "bermudas", label: "Bermudas e casual", Icon: Palmtree, gradient: "from-lime-300 to-teal-600" },
  { id: "cruz", label: "Produtos cristãos", Icon: Cross, gradient: "from-amber-300 to-yellow-600" },
  { id: "biblia", label: "Bíblia", Icon: BookOpenText, gradient: "from-amber-500 to-rose-700" },
  { id: "cosmeticos", label: "Cosméticos", Icon: Sparkles, gradient: "from-fuchsia-400 to-pink-500" },
  { id: "perfumes", label: "Perfumes", Icon: SprayCan, gradient: "from-amber-300 to-orange-500" },
  { id: "suplementos", label: "Suplementos", Icon: Pill, gradient: "from-emerald-400 to-teal-500" },
  { id: "academia", label: "Fitness", Icon: Dumbbell, gradient: "from-lime-400 to-emerald-500" },
  { id: "brinquedos", label: "Brinquedos", Icon: ToyBrick, gradient: "from-yellow-300 to-orange-400" },
  { id: "internet", label: "Internet", Icon: Wifi, gradient: "from-sky-400 to-blue-500" },
  { id: "chips", label: "Chips telefônicos", Icon: Smartphone, gradient: "from-cyan-400 to-sky-500" },
  { id: "maquininha", label: "Maquininha de cartão", Icon: CreditCard, gradient: "from-indigo-400 to-violet-500" },
  { id: "banco", label: "Conta bancária", Icon: Landmark, gradient: "from-blue-500 to-indigo-600" },
  { id: "bet", label: "Apostas", Icon: Dices, gradient: "from-orange-400 to-amber-500" },
  { id: "eletrodomesticos", label: "Eletrodomésticos", Icon: WashingMachine, gradient: "from-sky-300 to-indigo-500" },
  { id: "papelaria", label: "Papelaria e escritório", Icon: Paperclip, gradient: "from-cyan-300 to-teal-600" },
  { id: "eletronicos", label: "Eletrônicos", Icon: Laptop, gradient: "from-slate-400 to-slate-600" },
  { id: "audio", label: "Áudio", Icon: Headphones, gradient: "from-violet-400 to-purple-600" },
  { id: "casa", label: "Casa", Icon: Home, gradient: "from-teal-300 to-cyan-500" },
  { id: "moveis", label: "Móveis", Icon: Sofa, gradient: "from-amber-400 to-yellow-600" },
  { id: "restaurantes", label: "Restaurantes", Icon: UtensilsCrossed, gradient: "from-red-400 to-rose-600" },
  { id: "cafe", label: "Cafeteria", Icon: Coffee, gradient: "from-amber-600 to-orange-700" },
  { id: "mercado", label: "Mercado", Icon: ShoppingBasket, gradient: "from-green-400 to-emerald-600" },
  { id: "bebe", label: "Bebê", Icon: Baby, gradient: "from-pink-300 to-sky-400" },
  { id: "pet", label: "Pet shop", Icon: PawPrint, gradient: "from-orange-300 to-amber-500" },
  { id: "carros", label: "Automotivo", Icon: Car, gradient: "from-zinc-400 to-blue-600" },
  { id: "bike", label: "Bicicletas", Icon: Bike, gradient: "from-emerald-300 to-green-600" },
  { id: "viagens", label: "Viagens", Icon: Plane, gradient: "from-sky-300 to-indigo-500" },
  { id: "hoteis", label: "Hotéis", Icon: Hotel, gradient: "from-blue-300 to-cyan-600" },
  { id: "games", label: "Games", Icon: Gamepad2, gradient: "from-purple-500 to-fuchsia-600" },
  { id: "livros", label: "Livros", Icon: Book, gradient: "from-amber-300 to-red-400" },
  { id: "cursos", label: "Cursos", Icon: GraduationCap, gradient: "from-indigo-300 to-blue-600" },
  { id: "saude", label: "Saúde", Icon: Stethoscope, gradient: "from-teal-400 to-emerald-600" },
  { id: "beleza", label: "Salão e barbearia", Icon: Scissors, gradient: "from-rose-300 to-fuchsia-500" },
  { id: "joias", label: "Joias", Icon: Gem, gradient: "from-cyan-300 to-violet-500" },
  { id: "relogios", label: "Relógios", Icon: Watch, gradient: "from-slate-300 to-zinc-600" },
  { id: "calcados", label: "Calçados", Icon: Footprints, gradient: "from-orange-300 to-rose-500" },
  { id: "fotografia", label: "Fotografia", Icon: Camera, gradient: "from-zinc-400 to-indigo-600" },
  { id: "musica", label: "Música", Icon: Music, gradient: "from-fuchsia-400 to-indigo-500" },
  { id: "ferramentas", label: "Ferramentas", Icon: Wrench, gradient: "from-yellow-400 to-zinc-600" },
  { id: "construcao", label: "Construção", Icon: Hammer, gradient: "from-amber-500 to-stone-600" },
  { id: "natural", label: "Produtos naturais", Icon: Leaf, gradient: "from-lime-300 to-green-600" },
  { id: "flores", label: "Flores", Icon: Flower2, gradient: "from-pink-300 to-rose-500" },
  { id: "presentes", label: "Presentes", Icon: Gift, gradient: "from-red-400 to-pink-600" },
  { id: "cupons", label: "Cupons", Icon: Ticket, gradient: "from-indigo-400 to-cyan-500" },
  { id: "streaming", label: "Streaming", Icon: Tv, gradient: "from-violet-500 to-blue-600" },
  { id: "assinaturas", label: "Assinaturas", Icon: Cloud, gradient: "from-sky-300 to-violet-500" },
  { id: "investimentos", label: "Investimentos", Icon: PiggyBank, gradient: "from-emerald-400 to-cyan-600" },
  { id: "cripto", label: "Cripto", Icon: Bitcoin, gradient: "from-yellow-400 to-orange-600" },
  { id: "contas", label: "Contas e boletos", Icon: Receipt, gradient: "from-teal-300 to-blue-500" },
  { id: "entregas", label: "Entregas", Icon: Truck, gradient: "from-orange-400 to-red-500" },
  { id: "empresas", label: "Serviços para empresas", Icon: Building2, gradient: "from-indigo-300 to-slate-600" },
  { id: "energia", label: "Energia solar", Icon: Sun, gradient: "from-yellow-300 to-amber-600" },
];

export const SOCIAL_ICON_IDS = [
  "instagram",
  "youtube",
  "facebook",
  "twitter",
  "linkedin",
  "send",
  "message-circle",
  "music",
  "globe",
  "mail",
] as const;

export function getIcon(id: string): IconDef {
  return ICON_LIBRARY.find((i) => i.id === id) ?? ICON_LIBRARY[0]!;
}
